before_install:
  - npm update -g npm
  - npm install -g grunt-cli
before_script: grunt test
install: bin/install.sh
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
  - "stable"
script:
  - grunt build
