before_install: npm install -g grunt-cli
before_script:
  - grunt test
  - grunt jsdoc
install: bin/install.sh
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
  - "stable"
notifications:
  email: webmaster@christiangrete.com
script:
  - grunt build
